# Generated by Django 4.2.13 on 2024-07-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodega',
            table='BodegaProd',
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='Carro',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='CateProd',
        ),
        migrations.AlterModelTable(
            name='detalleboleta',
            table='BoletaDet',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='Usuario',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Prod',
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicicleta', models.CharField(max_length=100, verbose_name='Descripción de la bicicleta')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('hora_programada', models.TimeField(verbose_name='Hora programada')),
                ('tipo_servicio', models.CharField(max_length=100, verbose_name='Tipo de Servicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'Mantenimiento',
                'ordering': ['fecha_programada', 'hora_programada'],
            },
        ),
    ]
