# Generated by Django 4.2.13 on 2024-07-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bodega_table_alter_carrito_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodega',
            table='Bodega',
        ),
    ]
