# Generated by Django 4.2.13 on 2024-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mantenimiento_descripcion_problema_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion_problema',
            field=models.TextField(verbose_name='Descripción del problema'),
        ),
        migrations.AddConstraint(
            model_name='mantenimiento',
            constraint=models.UniqueConstraint(fields=('fecha_programada', 'hora_programada'), name='unique_fecha_hora'),
        ),
    ]
