# Generated by Django 4.2.13 on 2024-07-10 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bicicleta_arriendo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arriendo',
            options={'verbose_name': 'Arriendo', 'verbose_name_plural': 'Arriendos'},
        ),
        migrations.AlterModelOptions(
            name='bicicleta',
            options={'verbose_name': 'Bicicleta', 'verbose_name_plural': 'Bicicletas'},
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfil', verbose_name='Cliente'),
        ),
        migrations.AlterModelTable(
            name='arriendo',
            table='arriendos',
        ),
        migrations.AlterModelTable(
            name='bicicleta',
            table='bicicletas',
        ),
    ]
